---
env: 
  browser: true
  es6: true
ignorePatterns: ['*.conf.js', '*.config.js']
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  yoda: off
  no-plusplus: off